// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('breadcrumbs test', function() {
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('click through mobile buttons (de)', async function() {
    // Test name: click through mobile buttons (de)
    // Step # | name | target | value
    // 1 | open | /de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022 | 
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    // 2 | setWindowSize | 200x400 | 
    await driver.manage().window().setRect({ width: 200, height: 400 })
    // 3 | click | id=mobilebutton catalog | 
    await driver.findElement(By.id("mobilebutton catalog")).click()
    // 4 | click | id=CHOP 1 | 
    await driver.findElement(By.id("CHOP 1")).click()
    // 5 | click | id=mobilebutton version | 
    await driver.findElement(By.id("mobilebutton version")).click()
    // 6 | click | id=CHOP_2013 | 
    await driver.findElement(By.id("CHOP_2013")).click()
    // 7 | click | id=mobilebutton version | 
    await driver.findElement(By.id("mobilebutton version")).click()
    // 8 | click | id=CHOP_2018 | 
    await driver.findElement(By.id("CHOP_2018")).click()
    // 9 | click | id=mobilebutton catalog | 
    await driver.findElement(By.id("mobilebutton catalog")).click()
    // 10 | click | id=SwissDRG 2 | 
    await driver.findElement(By.id("SwissDRG 2")).click()
    // 11 | click | linkText=MDC 03: | 
    await driver.findElement(By.linkText("MDC 03:")).click()
    // 12 | click | linkText=Andere Partition: | 
    await driver.findElement(By.linkText("Andere Partition:")).click()
    // 13 | click | linkText=D40: | 
    await driver.findElement(By.linkText("D40:")).click()
    // 14 | click | id=mobilebutton catalog | 
    await driver.findElement(By.id("mobilebutton catalog")).click()
    // 15 | click | id=SwissDRG 2 | 
    await driver.findElement(By.id("SwissDRG 2")).click()
    // 16 | click | id=mobilebutton catalog | 
    await driver.findElement(By.id("mobilebutton catalog")).click()
    // 17 | click | id=CHOP 1 | 
    await driver.findElement(By.id("CHOP 1")).click()
    // 18 | click | linkText=C1: | 
    await driver.findElement(By.linkText("C1:")).click()
    // 19 | click | linkText=01: | 
    await driver.findElement(By.linkText("01:")).click()
    // 20 | click | id=mobilebutton catalog | 
    await driver.findElement(By.id("mobilebutton catalog")).click()
    // 21 | click | id=ICD 0 | 
    await driver.findElement(By.id("ICD 0")).click()
    // 22 | click | linkText=V: | 
    await driver.findElement(By.linkText("V:")).click()
    // 23 | click | id=mobilebutton version | 
    await driver.findElement(By.id("mobilebutton version")).click()
    // 24 | click | id=ICD10-GM-2018 | 
    await driver.findElement(By.id("ICD10-GM-2018")).click()
    // 25 | click | linkText=III: | 
    await driver.findElement(By.linkText("III:")).click()
  })
  it('breadcrumbs in mobile', async function() {
    // Test name: breadcrumbs in mobile
    // Step # | name | target | value
    // 1 | open | /de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022 | 
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    // 2 | setWindowSize | 200x400 | 
    await driver.manage().window().setRect({ width: 200, height: 400 })
    // 3 | click | linkText=III: | 
    await driver.findElement(By.linkText("III:")).click()
    // 4 | click | linkText=D55-D59: | 
    await driver.findElement(By.linkText("D55-D59:")).click()
    // 5 | click | linkText=III | 
    await driver.findElement(By.linkText("III")).click()
    // 6 | click | linkText=D65-D69: | 
    await driver.findElement(By.linkText("D65-D69:")).click()
    // 7 | runScript | window.scrollTo(0,0) | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 8 | click | linkText=D69: | 
    await driver.findElement(By.linkText("D69:")).click()
    // 9 | click | linkText=D69.0: | 
    await driver.findElement(By.linkText("D69.0:")).click()
    // 10 | mouseOver | linkText=ICD10-GM-2022 | 
    {
      const element = await driver.findElement(By.linkText("ICD10-GM-2022"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 11 | click | linkText=ICD10-GM-2022 | 
    await driver.findElement(By.linkText("ICD10-GM-2022")).click()
    // 12 | click | id=mobilebutton version | 
    await driver.findElement(By.id("mobilebutton version")).click()
    // 13 | click | id=ICD10-GM-2014 | 
    await driver.findElement(By.id("ICD10-GM-2014")).click()
    // 14 | click | linkText=XII: | 
    await driver.findElement(By.linkText("XII:")).click()
    // 15 | click | linkText=L00-L08: | 
    await driver.findElement(By.linkText("L00-L08:")).click()
    // 16 | mouseOver | linkText=XII | 
    {
      const element = await driver.findElement(By.linkText("XII"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 17 | click | linkText=XII | 
    await driver.findElement(By.linkText("XII")).click()
    // 18 | mouseOver | id=mobilebutton catalog | 
    {
      const element = await driver.findElement(By.id("mobilebutton catalog"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 19 | click | id=mobilebutton catalog | 
    await driver.findElement(By.id("mobilebutton catalog")).click()
    // 20 | mouseOut | id=mobilebutton catalog | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 21 | click | id=MiGeL 4 | 
    await driver.findElement(By.id("MiGeL 4")).click()
    // 22 | click | id=mobilebutton catalog | 
    await driver.findElement(By.id("mobilebutton catalog")).click()
    // 23 | click | id=SwissDRG 2 | 
    await driver.findElement(By.id("SwissDRG 2")).click()
    // 24 | click | css=li:nth-child(3) | 
    await driver.findElement(By.css("li:nth-child(3)")).click()
    // 25 | click | linkText=MDC 03: | 
    await driver.findElement(By.linkText("MDC 03:")).click()
    // 26 | click | linkText=Medizinische Partition: | 
    await driver.findElement(By.linkText("Medizinische Partition:")).click()
    // 27 | click | linkText=D62: | 
    await driver.findElement(By.linkText("D62:")).click()
    // 28 | click | linkText=D62B: | 
    await driver.findElement(By.linkText("D62B:")).click()
    // 29 | mouseOver | linkText=Medizinische Partition | 
    {
      const element = await driver.findElement(By.linkText("Medizinische Partition"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 30 | click | linkText=Medizinische Partition | 
    await driver.findElement(By.linkText("Medizinische Partition")).click()
    // 31 | click | linkText=D60: | 
    await driver.findElement(By.linkText("D60:")).click()
    // 32 | mouseOver | linkText=MDC 03 | 
    {
      const element = await driver.findElement(By.linkText("MDC 03"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 33 | click | linkText=MDC 03 | 
    await driver.findElement(By.linkText("MDC 03")).click()
    // 34 | click | linkText=Operative Partition: | 
    await driver.findElement(By.linkText("Operative Partition:")).click()
    // 35 | mouseOver | linkText=eonum | 
    {
      const element = await driver.findElement(By.linkText("eonum"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 36 | mouseOut | linkText=eonum | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 37 | click | id=mobilebutton catalog | 
    await driver.findElement(By.id("mobilebutton catalog")).click()
    // 38 | click | id=CHOP 1 | 
    await driver.findElement(By.id("CHOP 1")).click()
    // 39 | click | linkText=C4: | 
    await driver.findElement(By.linkText("C4:")).click()
    // 40 | click | linkText=20: | 
    await driver.findElement(By.linkText("20:")).click()
    // 41 | click | linkText=C4 | 
    await driver.findElement(By.linkText("C4")).click()
    // 42 | click | linkText=18: | 
    await driver.findElement(By.linkText("18:")).click()
    // 43 | click | linkText=18.3: | 
    await driver.findElement(By.linkText("18.3:")).click()
    // 44 | click | linkText=18.31: | 
    await driver.findElement(By.linkText("18.31:")).click()
    // 45 | click | linkText=CHOP 2022 | 
    await driver.findElement(By.linkText("CHOP 2022")).click()
  })
  it('testing breadcrumbs de', async function() {
    // Test name: testing breadcrumbs de
    // Step # | name | target | value
    // 1 | open | /de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022 | 
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    // 2 | setWindowSize | 1200x800 | 
    await driver.manage().window().setRect({ width: 1200, height: 800 })
    // 3 | click | linkText=I: | 
    await driver.findElement(By.linkText("I:")).click()
    // 4 | click | linkText=A00-A09: | 
    await driver.findElement(By.linkText("A00-A09:")).click()
    // 5 | click | linkText=A01: | 
    await driver.findElement(By.linkText("A01:")).click()
    // 6 | click | linkText=A01.0: | 
    await driver.findElement(By.linkText("A01.0:")).click()
    // 7 | runScript | window.scrollTo(0,248) | 
    await driver.executeScript("window.scrollTo(0,248)")
    // 8 | click | linkText=A01.2: | 
    await driver.findElement(By.linkText("A01.2:")).click()
    // 9 | click | linkText=A01.3: | 
    await driver.findElement(By.linkText("A01.3:")).click()
    // 10 | click | linkText=A00-A09 | 
    await driver.findElement(By.linkText("A00-A09")).click()
    // 11 | click | linkText=A01: | 
    await driver.findElement(By.linkText("A01:")).click()
    // 12 | click | linkText=A01.0: | 
    await driver.findElement(By.linkText("A01.0:")).click()
    // 13 | mouseOver | linkText=eonum | 
    {
      const element = await driver.findElement(By.linkText("eonum"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 14 | click | linkText=I | 
    await driver.findElement(By.linkText("I")).click()
    // 15 | click | linkText=B00-B09: | 
    await driver.findElement(By.linkText("B00-B09:")).click()
    // 16 | click | linkText=B08: | 
    await driver.findElement(By.linkText("B08:")).click()
    // 17 | click | id=CHOP | 
    await driver.findElement(By.id("CHOP")).click()
    // 18 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 19 | click | id=CHOP_2018 | 
    await driver.findElement(By.id("CHOP_2018")).click()
    // 20 | click | linkText=C4: | 
    await driver.findElement(By.linkText("C4:")).click()
    // 21 | click | linkText=20: | 
    await driver.findElement(By.linkText("20:")).click()
    // 22 | click | linkText=20.1: | 
    await driver.findElement(By.linkText("20.1:")).click()
    // 23 | click | linkText=20.4: | 
    await driver.findElement(By.linkText("20.4:")).click()
    // 24 | click | linkText=20.41: | 
    await driver.findElement(By.linkText("20.41:")).click()
    // 25 | click | id=SwissDRG | 
    await driver.findElement(By.id("SwissDRG")).click()
    // 26 | mouseOver | id=SwissDRG | 
    {
      const element = await driver.findElement(By.id("SwissDRG"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 27 | mouseOut | id=SwissDRG | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 28 | click | linkText=MDC 05: | 
    await driver.findElement(By.linkText("MDC 05:")).click()
    // 29 | click | css=div:nth-child(3) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(3) #buttonversion")).click()
    // 30 | mouseOver | css=div:nth-child(3) #buttonversion | 
    {
      const element = await driver.findElement(By.css("div:nth-child(3) #buttonversion"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 31 | mouseOut | css=.show > #buttonversion | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 32 | click | id=V8.0 | 
    await driver.findElement(By.id("V8.0")).click()
    // 33 | click | linkText=MDC 06: | 
    await driver.findElement(By.linkText("MDC 06:")).click()
    // 34 | click | linkText=Andere Partition: | 
    await driver.findElement(By.linkText("Andere Partition:")).click()
    // 35 | click | linkText=G46: | 
    await driver.findElement(By.linkText("G46:")).click()
    // 36 | click | linkText=Andere Partition | 
    await driver.findElement(By.linkText("Andere Partition")).click()
    // 37 | click | linkText=G40: | 
    await driver.findElement(By.linkText("G40:")).click()
    // 38 | click | linkText=MDC 06 | 
    await driver.findElement(By.linkText("MDC 06")).click()
    // 39 | click | linkText=Andere Partition: | 
    await driver.findElement(By.linkText("Andere Partition:")).click()
    // 40 | click | linkText=G40: | 
    await driver.findElement(By.linkText("G40:")).click()
    // 41 | click | linkText=G40Z: | 
    await driver.findElement(By.linkText("G40Z:")).click()
    // 42 | mouseOver | linkText=eonum | 
    {
      const element = await driver.findElement(By.linkText("eonum"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 43 | click | id=TARMED | 
    await driver.findElement(By.id("TARMED")).click()
    // 44 | click | linkText=07: | 
    await driver.findElement(By.linkText("07:")).click()
    // 45 | click | css=ul > li:nth-child(2) | 
    await driver.findElement(By.css("ul > li:nth-child(2)")).click()
    // 46 | click | linkText=07.02: | 
    await driver.findElement(By.linkText("07.02:")).click()
    // 47 | click | linkText=07.0140: | 
    await driver.findElement(By.linkText("07.0140:")).click()
    // 48 | click | css=ul > li:nth-child(2) | 
    await driver.findElement(By.css("ul > li:nth-child(2)")).click()
    // 49 | click | linkText=07.0120: | 
    await driver.findElement(By.linkText("07.0120:")).click()
    // 50 | click | linkText=07.0260: | 
    await driver.findElement(By.linkText("07.0260:")).click()
    // 51 | click | linkText=07.0250: | 
    await driver.findElement(By.linkText("07.0250:")).click()
    // 52 | click | linkText=07 | 
    await driver.findElement(By.linkText("07")).click()
    // 53 | click | linkText=TARMED 01.09 | 
    await driver.findElement(By.linkText("TARMED 01.09")).click()
    // 54 | click | linkText=11: | 
    await driver.findElement(By.linkText("11:")).click()
  })
  it('testing breadcrumbs fr', async function() {
    // Test name: testing breadcrumbs fr
    // Step # | name | target | value
    // 1 | open | /fr/ICD/ICD10-GM-2020/icd_chapters/ICD10-GM-2020 | 
    await driver.get("http://localhost:3000/fr/ICD/ICD10-GM-2020/icd_chapters/ICD10-GM-2020")
    // 2 | click | linkText=I: | 
    await driver.findElement(By.linkText("I:")).click()
    // 3 | click | linkText=A00-A09: | 
    await driver.findElement(By.linkText("A00-A09:")).click()
    // 4 | click | linkText=A01: | 
    await driver.findElement(By.linkText("A01:")).click()
    // 5 | click | linkText=A01.0: | 
    await driver.findElement(By.linkText("A01.0:")).click()
    // 6 | runScript | window.scrollTo(0,248) | 
    await driver.executeScript("window.scrollTo(0,248)")
    // 7 | click | linkText=A01.2: | 
    await driver.findElement(By.linkText("A01.2:")).click()
    // 8 | click | linkText=A01.3: | 
    await driver.findElement(By.linkText("A01.3:")).click()
    // 9 | click | linkText=A00-A09 | 
    await driver.findElement(By.linkText("A00-A09")).click()
    // 10 | click | linkText=A01: | 
    await driver.findElement(By.linkText("A01:")).click()
    // 11 | click | linkText=A01.0: | 
    await driver.findElement(By.linkText("A01.0:")).click()
    // 12 | mouseOver | linkText=eonum | 
    {
      const element = await driver.findElement(By.linkText("eonum"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 13 | click | linkText=I | 
    await driver.findElement(By.linkText("I")).click()
    // 14 | click | linkText=B00-B09: | 
    await driver.findElement(By.linkText("B00-B09:")).click()
    // 15 | click | linkText=B08: | 
    await driver.findElement(By.linkText("B08:")).click()
    // 16 | click | id=CHOP | 
    await driver.findElement(By.id("CHOP")).click()
    // 17 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 18 | click | id=CHOP_2018 | 
    await driver.findElement(By.id("CHOP_2018")).click()
    // 19 | click | linkText=C4: | 
    await driver.findElement(By.linkText("C4:")).click()
    // 20 | click | linkText=20: | 
    await driver.findElement(By.linkText("20:")).click()
    // 21 | click | linkText=20.1: | 
    await driver.findElement(By.linkText("20.1:")).click()
    // 22 | click | linkText=20.4: | 
    await driver.findElement(By.linkText("20.4:")).click()
    // 23 | click | linkText=20.41: | 
    await driver.findElement(By.linkText("20.41:")).click()
    // 24 | click | id=SwissDRG | 
    await driver.findElement(By.id("SwissDRG")).click()
    // 25 | mouseOver | id=SwissDRG | 
    {
      const element = await driver.findElement(By.id("SwissDRG"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 26 | mouseOut | id=SwissDRG | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 27 | click | linkText=MDC 05: | 
    await driver.findElement(By.linkText("MDC 05:")).click()
    // 28 | click | css=div:nth-child(3) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(3) #buttonversion")).click()
    // 29 | mouseOver | css=div:nth-child(3) #buttonversion | 
    {
      const element = await driver.findElement(By.css("div:nth-child(3) #buttonversion"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 30 | mouseOut | css=.show > #buttonversion | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 31 | click | id=V8.0 | 
    await driver.findElement(By.id("V8.0")).click()
    // 32 | click | linkText=MDC 06: | 
    await driver.findElement(By.linkText("MDC 06:")).click()
    // 33 | click | linkText=Autre partition: | 
    await driver.findElement(By.linkText("Autre partition:")).click()
    // 34 | click | linkText=G46: | 
    await driver.findElement(By.linkText("G46:")).click()
    // 35 | click | linkText=Autre partition | 
    await driver.findElement(By.linkText("Autre partition")).click()
    // 36 | click | linkText=G40: | 
    await driver.findElement(By.linkText("G40:")).click()
    // 37 | click | linkText=MDC 06 | 
    await driver.findElement(By.linkText("MDC 06")).click()
    // 38 | click | linkText=Autre partition: | 
    await driver.findElement(By.linkText("Autre partition:")).click()
    // 39 | click | linkText=G40: | 
    await driver.findElement(By.linkText("G40:")).click()
    // 40 | click | linkText=G40Z: | 
    await driver.findElement(By.linkText("G40Z:")).click()
    // 41 | mouseOver | linkText=eonum | 
    {
      const element = await driver.findElement(By.linkText("eonum"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 42 | click | id=TARMED | 
    await driver.findElement(By.id("TARMED")).click()
    // 43 | click | linkText=07: | 
    await driver.findElement(By.linkText("07:")).click()
    // 44 | click | css=ul > li:nth-child(2) | 
    await driver.findElement(By.css("ul > li:nth-child(2)")).click()
    // 45 | click | linkText=07.02: | 
    await driver.findElement(By.linkText("07.02:")).click()
    // 46 | click | linkText=07.0140: | 
    await driver.findElement(By.linkText("07.0140:")).click()
    // 47 | click | css=ul > li:nth-child(2) | 
    await driver.findElement(By.css("ul > li:nth-child(2)")).click()
    // 48 | click | linkText=07.0120: | 
    await driver.findElement(By.linkText("07.0120:")).click()
    // 49 | click | linkText=07.0260: | 
    await driver.findElement(By.linkText("07.0260:")).click()
    // 50 | click | linkText=07.0250: | 
    await driver.findElement(By.linkText("07.0250:")).click()
    // 51 | click | linkText=07 | 
    await driver.findElement(By.linkText("07")).click()
    // 52 | click | linkText=TARMED 01.09 | 
    await driver.findElement(By.linkText("TARMED 01.09")).click()
    // 53 | click | linkText=11: | 
    await driver.findElement(By.linkText("11:")).click()
  })
  it('icd clicking from I to A00.0 (de, 2008)', async function() {
    // Test name: icd clicking from I to A00.0 (de, 2008)
    // Step # | name | target | value
    // 1 | open | /de/ICD/ICD10-GM-2008/icd_chapters/ICD10-GM-2008 | 
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2008/icd_chapters/ICD10-GM-2008")
    // 2 | click | linkText=I: | 
    await driver.findElement(By.linkText("I:")).click()
    // 3 | click | linkText=A00-A09: | 
    await driver.findElement(By.linkText("A00-A09:")).click()
    // 4 | click | linkText=A00: | 
    await driver.findElement(By.linkText("A00:")).click()
    // 5 | click | linkText=A00.0: | 
    await driver.findElement(By.linkText("A00.0:")).click()
    // 6 | click | linkText=A00 | 
    await driver.findElement(By.linkText("A00")).click()
    // 7 | click | linkText=A00-A09 | 
    await driver.findElement(By.linkText("A00-A09")).click()
    // 8 | click | linkText=I | 
    await driver.findElement(By.linkText("I")).click()
    // 9 | click | linkText=ICD10-GM-2008 | 
    await driver.findElement(By.linkText("ICD10-GM-2008")).click()
  })
  it('icd clicking from I to A00.0 (de, 2022)', async function() {
    // Test name: icd clicking from I to A00.0 (de, 2022)
    // Step # | name | target | value
    // 1 | open | /de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022 | 
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    // 2 | click | linkText=I: | 
    await driver.findElement(By.linkText("I:")).click()
    // 3 | click | linkText=A00-A09: | 
    await driver.findElement(By.linkText("A00-A09:")).click()
    // 4 | click | linkText=A00: | 
    await driver.findElement(By.linkText("A00:")).click()
    // 5 | click | linkText=A00.0: | 
    await driver.findElement(By.linkText("A00.0:")).click()
    // 6 | click | linkText=A00 | 
    await driver.findElement(By.linkText("A00")).click()
    // 7 | click | linkText=A00-A09 | 
    await driver.findElement(By.linkText("A00-A09")).click()
    // 8 | click | linkText=I | 
    await driver.findElement(By.linkText("I")).click()
    // 9 | click | linkText=ICD10-GM-2022 | 
    await driver.findElement(By.linkText("ICD10-GM-2022")).click()
  })
  it('Chop version newer to older and back (de)', async function() {
    // Test name: Chop version newer to older and back (de)
    // Step # | name | target | value
    // 1 | open | /de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022 | 
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    // 2 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 3 | click | id=CHOP | 
    await driver.findElement(By.id("CHOP")).click()
    // 4 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 5 | click | id=CHOP_2021 | 
    await driver.findElement(By.id("CHOP_2021")).click()
    // 6 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 7 | click | id=CHOP_2019 | 
    await driver.findElement(By.id("CHOP_2019")).click()
    // 8 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 9 | click | id=CHOP_2018 | 
    await driver.findElement(By.id("CHOP_2018")).click()
    // 10 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 11 | click | id=CHOP_2016 | 
    await driver.findElement(By.id("CHOP_2016")).click()
    // 12 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 13 | click | id=CHOP_2015 | 
    await driver.findElement(By.id("CHOP_2015")).click()
    // 14 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 15 | click | id=CHOP_2018 | 
    await driver.findElement(By.id("CHOP_2018")).click()
    // 16 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 17 | click | id=CHOP_2020 | 
    await driver.findElement(By.id("CHOP_2020")).click()
    // 18 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 19 | click | id=CHOP_2022 | 
    await driver.findElement(By.id("CHOP_2022")).click()
  })
  it('chop clicking from C0 to 00.0 (de)', async function() {
    // Test name: chop clicking from C0 to 00.0 (de)
    // Step # | name | target | value
    // 1 | open | http://localhost:3000/de/CHOP/CHOP_2022/chop_chapters/CHOP_2022 | 
    await driver.get("http://localhost:3000/de/CHOP/CHOP_2022/chop_chapters/CHOP_2022")
    // 2 | click | linkText=C0: | 
    await driver.findElement(By.linkText("C0:")).click()
    // 3 | click | linkText=00: | 
    await driver.findElement(By.linkText("00:")).click()
    // 4 | click | linkText=00.0: | 
    await driver.findElement(By.linkText("00.0:")).click()
    // 5 | click | linkText=00 | 
    await driver.findElement(By.linkText("00")).click()
    // 6 | click | linkText=C0 | 
    await driver.findElement(By.linkText("C0")).click()
    // 7 | click | linkText=CHOP 2022 | 
    await driver.findElement(By.linkText("CHOP 2022")).click()
  })
})
