// Generated by Selenium IDE
const assert = require('assert')
const { Builder, By, Key, until } = require('selenium-webdriver')
require('selenium-webdriver/firefox')
require('geckodriver')
describe('Default Suite', function() {
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('clicking from one catalog to another (de)', async function() {
    // Test name: clicking from one catalog to another (de)
    // Step # | name | target | value
    // 1 | open | /de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022 | 
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    // 2 | click | css=div:nth-child(3) .customButton:nth-child(1) | 
    await driver.findElement(By.css("div:nth-child(3) .customButton:nth-child(1)")).click()
    // 3 | click | css=div:nth-child(4) > div > .catalogButtons > .customButton:nth-child(1) | 
    await driver.findElement(By.css("div:nth-child(4) > div > .catalogButtons > .customButton:nth-child(1)")).click()
    // 4 | click | css=div:nth-child(2) > div > .catalogButtons > .customButton:nth-child(1) | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > .customButton:nth-child(1)")).click()
    // 5 | click | css=div:nth-child(1) > div > .catalogButtons > .customButton:nth-child(1) | 
    await driver.findElement(By.css("div:nth-child(1) > div > .catalogButtons > .customButton:nth-child(1)")).click()
    // 6 | click | css=div:nth-child(4) > div > .catalogButtons > .customButton:nth-child(1) | 
    await driver.findElement(By.css("div:nth-child(4) > div > .catalogButtons > .customButton:nth-child(1)")).click()
    // 7 | click | name=MiGeL | 
    await driver.findElement(By.name("MiGeL")).click()
    // 8 | click | name=AL | 
    await driver.findElement(By.name("AL")).click()
    // 9 | click | css=div:nth-child(4) > div > .catalogButtons > .customButton:nth-child(1) | 
    await driver.findElement(By.css("div:nth-child(4) > div > .catalogButtons > .customButton:nth-child(1)")).click()
    // 10 | click | name=DRUG | 
    await driver.findElement(By.name("DRUG")).click()
    // 11 | click | css=div:nth-child(2) > div > .catalogButtons > .customButton:nth-child(1) | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > .customButton:nth-child(1)")).click()
    // 12 | click | css=div:nth-child(1) > div > .catalogButtons > .customButton:nth-child(1) | 
    await driver.findElement(By.css("div:nth-child(1) > div > .catalogButtons > .customButton:nth-child(1)")).click()
    // 13 | click | css=div:nth-child(3) .customButton:nth-child(1) | 
    await driver.findElement(By.css("div:nth-child(3) .customButton:nth-child(1)")).click()
    // 14 | click | css=div:nth-child(4) > div > .catalogButtons > .customButton:nth-child(1) | 
    await driver.findElement(By.css("div:nth-child(4) > div > .catalogButtons > .customButton:nth-child(1)")).click()
    // 15 | click | name=DRUG | 
    await driver.findElement(By.name("DRUG")).click()
  })
  it('icd version newer to older and back (de)', async function() {
    // Test name: icd version newer to older and back (de)
    // Step # | name | target | value
    // 1 | open | /de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022 | 
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    // 2 | setWindowSize | 1042x796 | 
    await driver.manage().window().setRect({width: 1042, height: 796} )
    // 4 | mouseOver | id=buttonversion |
    {
      let element = await driver.findElement(By.id("buttonversion"))
      const actions = driver.actions({bridge: true});
      await actions.move({origin:element}).perform()
    }
    // 3 | click | id=buttonversion |
    await driver.findElement(By.id("buttonversion")).click()

    // 6 | click | id=ICD10-GM-2021 |
    await driver.findElement(By.id("ICD10-GM-2021")).click()
    // 7 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 8 | click | id=ICD10-GM-2020 | 
    await driver.findElement(By.id("ICD10-GM-2020")).click()
    // 9 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 10 | click | id=ICD10-GM-2018 | 
    await driver.findElement(By.id("ICD10-GM-2018")).click()
    // 11 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 12 | click | id=ICD10-GM-2015 | 
    await driver.findElement(By.id("ICD10-GM-2015")).click()
    // 13 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 14 | click | id=ICD10-GM-2013 | 
    await driver.findElement(By.id("ICD10-GM-2013")).click()
    // 15 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 16 | click | id=ICD10-GM-2011 | 
    await driver.findElement(By.id("ICD10-GM-2011")).click()
    // 17 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 18 | click | id=ICD10-GM-2008 | 
    await driver.findElement(By.id("ICD10-GM-2008")).click()
    // 19 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 20 | click | id=ICD10-GM-2019 | 
    await driver.findElement(By.id("ICD10-GM-2019")).click()
    // 21 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 22 | click | id=ICD10-GM-2021 | 
    await driver.findElement(By.id("ICD10-GM-2021")).click()
  })
  it('changing languages', async function() {
    // Test name: changing languages
    // Step # | name | target | value
    // 1 | open | /de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022 | 
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    // 2 | click | css=.language-btn:nth-child(2) | 
    await driver.findElement(By.css(".language-btn:nth-child(2)")).click()
    // 3 | click | css=.language-btn:nth-child(3) | 
    await driver.findElement(By.css(".language-btn:nth-child(3)")).click()
    // 4 | click | css=.language-btn:nth-child(4) | 
    await driver.findElement(By.css(".language-btn:nth-child(4)")).click()
    // 5 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 6 | click | css=div:nth-child(3) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(3) #buttonversion")).click()
    // 7 | click | css=div:nth-child(4) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(4) #buttonversion")).click()
    // 8 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 9 | click | id=ICD10-GM-2020 | 
    await driver.findElement(By.id("ICD10-GM-2020")).click()
    // 10 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 12 | mouseOver | css=.language-btn:nth-child(2) |
    {
      const element = await driver.findElement(By.css(".language-btn:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 13 | mouseOut | css=.language-btn:nth-child(2) |
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 11 | click | css=.language-btn:nth-child(3) |
    await driver.findElement(By.css(".language-btn:nth-child(3)")).click()
    // 14 | click | id=buttonversion |
    await driver.findElement(By.id("buttonversion")).click()
    // 15 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 16 | click | css=.language-btn:nth-child(2) | 
    await driver.findElement(By.css(".language-btn:nth-child(2)")).click()
    // 17 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 18 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 19 | click | css=div:nth-child(3) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(3) #buttonversion")).click()
    // 20 | click | id=V8.0 | 
    await driver.findElement(By.id("V8.0")).click()
    // 21 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 22 | click | id=ICD10-GM-2021 | 
    await driver.findElement(By.id("ICD10-GM-2021")).click()
    // 23 | click | css=.langBtn:nth-child(1) | 
    await driver.findElement(By.css(".langBtn:nth-child(1)")).click()
    // 24 | mouseOver | css=div:nth-child(3) #buttonversion | 
    {
      const element = await driver.findElement(By.css("div:nth-child(3) #buttonversion"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 25 | mouseOut | css=div:nth-child(3) #buttonversion | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
  it('click from button to other buttons version', async function() {
    // Test name: click from button to toher buttons version
    // Step # | name | target | value
    // 1 | open | /de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022 | 
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    // 2 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 3 | click | id=CHOP_2020 | 
    await driver.findElement(By.id("CHOP_2020")).click()
    // 4 | click | css=div:nth-child(3) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(3) #buttonversion")).click()
    // 5 | click | id=V8.0 | 
    await driver.findElement(By.id("V8.0")).click()
    // 6 | click | css=div:nth-child(4) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(4) #buttonversion")).click()
    // 7 | click | id=TARMED_01.09 | 
    await driver.findElement(By.id("TARMED_01.09")).click()
    // 8 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 9 | click | id=ICD10-GM-2019 | 
    await driver.findElement(By.id("ICD10-GM-2019")).click()
    // 10 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 11 | click | id=CHOP | 
    await driver.findElement(By.id("CHOP")).click()
  })
  it('hover over buttons', async function() {
    // Test name: hover over buttons
    // Step # | name | target | value
    // 1 | open | /de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022 | 
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    // 2 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 3 | click | id=CHOP | 
    await driver.findElement(By.id("CHOP")).click()
    // 4 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 5 | click | id=SwissDRG | 
    await driver.findElement(By.id("SwissDRG")).click()
    // 6 | click | css=div:nth-child(3) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(3) #buttonversion")).click()
    // 7 | click | id=TARMED | 
    await driver.findElement(By.id("TARMED")).click()
    // 8 | click | css=div:nth-child(4) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(4) #buttonversion")).click()
    // 9 | click | name=MiGeL | 
    await driver.findElement(By.name("MiGeL")).click()
    // 10 | click | name=AL | 
    await driver.findElement(By.name("AL")).click()
    // 11 | click | name=DRUG | 
    await driver.findElement(By.name("DRUG")).click()
    // 12 | click | id=ICD | 
    await driver.findElement(By.id("ICD")).click()
    // 13 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
  })
  it('clicking a version from a different catalog', async function() {
    // Test name: clicking a version from a different catalog
    // Step # | name | target | value
    // 1 | open | /de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022 | 
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    // 2 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 3 | click | id=CHOP_2020 | 
    await driver.findElement(By.id("CHOP_2020")).click()
    // 4 | click | css=div:nth-child(3) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(3) #buttonversion")).click()
    // 5 | click | id=V10.0 | 
    await driver.findElement(By.id("V10.0")).click()
    // 6 | click | css=div:nth-child(4) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(4) #buttonversion")).click()
    // 7 | click | id=TARMED_01.09 | 
    await driver.findElement(By.id("TARMED_01.09")).click()
    // 8 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 9 | click | id=ICD10-GM-2017 | 
    await driver.findElement(By.id("ICD10-GM-2017")).click()
    // 10 | click | css=.language-btn:nth-child(2) | 
    await driver.findElement(By.css(".language-btn:nth-child(2)")).click()
    // 11 | mouseOver | css=.language-btn:nth-child(1) | 
    {
      const element = await driver.findElement(By.css(".language-btn:nth-child(1)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 12 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 13 | click | id=ICD10-GM-2020 | 
    await driver.findElement(By.id("ICD10-GM-2020")).click()
    // 14 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 15 | click | id=CHOP_2020 | 
    await driver.findElement(By.id("CHOP_2020")).click()
    // 16 | click | css=div:nth-child(3) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(3) #buttonversion")).click()
    // 17 | click | id=V10.0 | 
    await driver.findElement(By.id("V10.0")).click()
    // 18 | click | css=div:nth-child(4) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(4) #buttonversion")).click()
    // 19 | click | id=TARMED_01.09 | 
    await driver.findElement(By.id("TARMED_01.09")).click()
    // 20 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 21 | click | id=CHOP_2020 | 
    await driver.findElement(By.id("CHOP_2020")).click()
    // 22 | click | css=.language-btn:nth-child(4) | 
    await driver.findElement(By.css(".language-btn:nth-child(4)")).click()
    // 23 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 24 | click | id=ICD10-GM-2020 | 
    await driver.findElement(By.id("ICD10-GM-2020")).click()
    // 25 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 26 | click | id=ICD10-GM-2022 | 
    await driver.findElement(By.id("ICD10-GM-2022")).click()
    // 27 | click | css=.language-btn:nth-child(3) | 
    await driver.findElement(By.css(".language-btn:nth-child(3)")).click()
    // 28 | mouseOver | id=SwissDRG | 
    {
      const element = await driver.findElement(By.id("SwissDRG"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 29 | mouseOut | id=SwissDRG | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 30 | click | css=div:nth-child(3) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(3) #buttonversion")).click()
    // 31 | click | id=V10.0 | 
    await driver.findElement(By.id("V10.0")).click()
  })
})
