// Generated by Selenium IDE
const assert = require('assert')
const { Builder, By, Key, until } = require('selenium-webdriver')
require('selenium-webdriver/chrome')
require('selenium-webdriver/firefox')
require('chromedriver')
require('geckodriver')
const firefox = require("selenium-webdriver");
describe('Default Suite', function() {
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build();
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })

  it('clicking from one catalog to another (de)', async function() {
    // Test name: clicking from one catalog to another (de)
    // Step # | name | target | value
    // 1 | open | /de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022 | 
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    // 3 | click | css=div:nth-child(3) .customButton:nth-child(1) |
    await driver.findElement(By.css("div:nth-child(3) .customButton:nth-child(1)")).click()
    // 4 | click | css=div:nth-child(4) > div > .catalogButtons > .customButton:nth-child(1) | 
    await driver.findElement(By.css("div:nth-child(4) > div > .catalogButtons > .customButton:nth-child(1)")).click()
    // 5 | click | css=div:nth-child(2) > div > .catalogButtons > .customButton:nth-child(1) | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > .customButton:nth-child(1)")).click()
    // 6 | click | css=div:nth-child(1) > div > .catalogButtons > .customButton:nth-child(1) | 
    await driver.findElement(By.css("div:nth-child(1) > div > .catalogButtons > .customButton:nth-child(1)")).click()
    // 7 | click | css=div:nth-child(4) > div > .catalogButtons > .customButton:nth-child(1) | 
    await driver.findElement(By.css("div:nth-child(4) > div > .catalogButtons > .customButton:nth-child(1)")).click()
    // 8 | click | name=MiGeL | 
    await driver.findElement(By.name("MiGeL")).click()
    // 9 | click | name=AL | 
    await driver.findElement(By.name("AL")).click()
    // 10 | click | css=div:nth-child(4) > div > .catalogButtons > .customButton:nth-child(1) | 
    await driver.findElement(By.css("div:nth-child(4) > div > .catalogButtons > .customButton:nth-child(1)")).click()
    // 11 | click | name=DRUG | 
    await driver.findElement(By.name("DRUG")).click()
    // 12 | click | css=div:nth-child(2) > div > .catalogButtons > .customButton:nth-child(1) | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > .customButton:nth-child(1)")).click()
    // 13 | click | css=div:nth-child(1) > div > .catalogButtons > .customButton:nth-child(1) | 
    await driver.findElement(By.css("div:nth-child(1) > div > .catalogButtons > .customButton:nth-child(1)")).click()
    // 14 | click | css=div:nth-child(3) .customButton:nth-child(1) | 
    await driver.findElement(By.css("div:nth-child(3) .customButton:nth-child(1)")).click()
    // 15 | click | css=div:nth-child(4) > div > .catalogButtons > .customButton:nth-child(1) | 
    await driver.findElement(By.css("div:nth-child(4) > div > .catalogButtons > .customButton:nth-child(1)")).click()
    // 16 | click | name=DRUG | 
    await driver.findElement(By.name("DRUG")).click()
  })
  it('changing languages', async function() {
    // Test name: changing languages
    // Step # | name | target | value
    // 1 | open | /de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022 | 
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    // 3 | click | css=.language-btn:nth-child(2) |
    await driver.findElement(By.css(".language-btn:nth-child(2)")).click()
    // 4 | click | css=.language-btn:nth-child(3) | 
    await driver.findElement(By.css(".language-btn:nth-child(3)")).click()
    // 5 | click | css=.language-btn:nth-child(4) | 
    await driver.findElement(By.css(".language-btn:nth-child(4)")).click()
    // 6 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 7 | click | css=div:nth-child(3) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(3) #buttonversion")).click()
    // 8 | click | css=div:nth-child(4) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(4) #buttonversion")).click()
    // 9 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 10 | click | id=ICD10-GM-2020 | 
    await driver.findElement(By.id("ICD10-GM-2020")).click()
    // 11 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 12 | click | css=.language-btn:nth-child(3) | 
    await driver.findElement(By.css(".language-btn:nth-child(3)")).click()
    // 13 | mouseOver | css=.language-btn:nth-child(2) | 
    {
      const element = await driver.findElement(By.css(".language-btn:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 14 | mouseOut | css=.language-btn:nth-child(2) | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 15 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 16 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 17 | click | css=.language-btn:nth-child(2) | 
    await driver.findElement(By.css(".language-btn:nth-child(2)")).click()
    // 18 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 19 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 20 | click | css=div:nth-child(3) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(3) #buttonversion")).click()
    // 21 | click | id=V8.0 | 
    await driver.findElement(By.id("V8.0")).click()
    // 22 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 23 | click | id=ICD10-GM-2021 | 
    await driver.findElement(By.id("ICD10-GM-2021")).click()
    // 24 | click | css=.langBtn:nth-child(1) | 
    await driver.findElement(By.css(".langBtn:nth-child(1)")).click()
    // 25 | mouseOver | css=div:nth-child(3) #buttonversion | 
    {
      const element = await driver.findElement(By.css("div:nth-child(3) #buttonversion"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 26 | mouseOut | css=div:nth-child(3) #buttonversion | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
  it('click from button to other buttons version', async function() {
    // Test name: click from button to toher buttons version
    // Step # | name | target | value
    // 1 | open | /de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022 | 
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    // 3 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 4 | click | id=CHOP_2020 | 
    await driver.findElement(By.id("CHOP")).click()
    // 5 | click | css=div:nth-child(3) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(3) #buttonversion")).click()
    // 6 | click | id=V8.0 | 
    await driver.findElement(By.id("V8.0")).click()
    // 7 | click | css=div:nth-child(4) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(4) #buttonversion")).click()
    // 8 | click | id=TARMED_01.09 | 
    await driver.findElement(By.id("TARMED_01.09")).click()
    // 9 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 10 | click | id=ICD10-GM-2019 | 
    await driver.findElement(By.id("ICD10-GM-2019")).click()
    // 11 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 12 | click | id=CHOP | 
    await driver.findElement(By.id("CHOP")).click()
  })
  it('hover over buttons', async function() {
    // Test name: hover over buttons
    // Step # | name | target | value
    // 1 | open | /de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022 | 
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    // 3 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 4 | click | id=CHOP | 
    await driver.findElement(By.id("CHOP")).click()
    // 5 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 6 | click | id=SwissDRG | 
    await driver.findElement(By.id("SwissDRG")).click()
    // 7 | click | css=div:nth-child(3) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(3) #buttonversion")).click()
    // 8 | click | id=TARMED | 
    await driver.findElement(By.id("TARMED")).click()
    // 9 | click | css=div:nth-child(4) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(4) #buttonversion")).click()
    // 10 | click | name=MiGeL | 
    await driver.findElement(By.name("MiGeL")).click()
    // 11 | click | name=AL | 
    await driver.findElement(By.name("AL")).click()
    // 12 | click | name=DRUG | 
    await driver.findElement(By.name("DRUG")).click()
    // 13 | click | id=ICD | 
    await driver.findElement(By.id("ICD")).click()
    // 14 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
  })
  it('clicking a version from a different catalog', async function() {
    // Test name: clicking a version from a different catalog
    // Step # | name | target | value
    // 1 | open | /de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022 | 
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    // 3 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 4 | click | id=CHOP_2020 | 
    await driver.findElement(By.id("CHOP_2020")).click()
    // 5 | click | css=div:nth-child(3) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(3) #buttonversion")).click()
    // 6 | click | id=V10.0 | 
    await driver.findElement(By.id("V10.0")).click()
    // 7 | click | css=div:nth-child(4) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(4) #buttonversion")).click()
    // 8 | click | id=TARMED_01.09 | 
    await driver.findElement(By.id("TARMED_01.09")).click()
    // 9 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 10 | click | id=ICD10-GM-2017 | 
    await driver.findElement(By.id("ICD10-GM-2017")).click()
    // 11 | click | css=.language-btn:nth-child(2) | 
    await driver.findElement(By.css(".language-btn:nth-child(2)")).click()
    // 12 | mouseOver | css=.language-btn:nth-child(1) | 
    {
      const element = await driver.findElement(By.css(".language-btn:nth-child(1)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 13 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 14 | click | id=ICD10-GM-2020 | 
    await driver.findElement(By.id("ICD10-GM-2020")).click()
    // 15 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 16 | click | id=CHOP_2020 | 
    await driver.findElement(By.id("CHOP_2020")).click()
    // 17 | click | css=div:nth-child(3) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(3) #buttonversion")).click()
    // 18 | click | id=V10.0 | 
    await driver.findElement(By.id("V10.0")).click()
    // 19 | click | css=div:nth-child(4) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(4) #buttonversion")).click()
    // 20 | click | id=TARMED_01.09 | 
    await driver.findElement(By.id("TARMED_01.09")).click()
    // 21 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 22 | click | id=CHOP_2020 | 
    await driver.findElement(By.id("CHOP_2020")).click()
    // 23 | click | css=.language-btn:nth-child(4) | 
    await driver.findElement(By.css(".language-btn:nth-child(4)")).click()
    // 24 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 25 | click | id=ICD10-GM-2020 | 
    await driver.findElement(By.id("ICD10-GM-2020")).click()
    // 26 | click | id=buttonversion | 
    await driver.findElement(By.id("buttonversion")).click()
    // 27 | click | id=ICD10-GM-2022 | 
    await driver.findElement(By.id("ICD10-GM-2022")).click()
    // 28 | click | css=.language-btn:nth-child(3) | 
    await driver.findElement(By.css(".language-btn:nth-child(3)")).click()
    // 29 | mouseOver | id=SwissDRG | 
    {
      const element = await driver.findElement(By.id("SwissDRG"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 30 | mouseOut | id=SwissDRG | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 31 | click | css=div:nth-child(3) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(3) #buttonversion")).click()
    // 32 | click | id=V10.0 | 
    await driver.findElement(By.id("V10.0")).click()
  })
  it('testing breadcrumbs de', async function() {
    // Test name: testing breadcrumbs de
    // Step # | name | target | value
    // 1 | open | /de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022 | 
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    // 3 | click | linkText=I: | 
    await driver.findElement(By.linkText("I:")).click()
    // 4 | click | linkText=A00-A09: | 
    await driver.findElement(By.linkText("A00-A09:")).click()
    // 5 | runScript | window.scrollTo(0,0) | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 6 | click | linkText=A01: | 
    await driver.findElement(By.linkText("A01:")).click()
    // 7 | click | linkText=A01.0: | 
    await driver.findElement(By.linkText("A01.0:")).click()
    // 8 | runScript | window.scrollTo(0,248) | 
    await driver.executeScript("window.scrollTo(0,248)")
    // 9 | click | linkText=A01.2: | 
    await driver.findElement(By.linkText("A01.2:")).click()
    // 10 | click | linkText=A01.3: | 
    await driver.findElement(By.linkText("A01.3:")).click()
    // 11 | click | linkText=A00-A09 | 
    await driver.findElement(By.linkText("A00-A09")).click()
    // 12 | click | linkText=A01: | 
    await driver.findElement(By.linkText("A01:")).click()
    // 13 | click | linkText=A01.0: | 
    await driver.findElement(By.linkText("A01.0:")).click()
    // 14 | mouseOver | linkText=eonum | 
    {
      const element = await driver.findElement(By.linkText("eonum"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 15 | click | linkText=I | 
    await driver.findElement(By.linkText("I")).click()
    // 16 | click | linkText=B00-B09: | 
    await driver.findElement(By.linkText("B00-B09:")).click()
    // 17 | click | linkText=B08: | 
    await driver.findElement(By.linkText("B08:")).click()
    // 18 | click | id=CHOP | 
    await driver.findElement(By.id("CHOP")).click()
    // 19 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 20 | click | id=CHOP_2018 | 
    await driver.findElement(By.id("CHOP_2018")).click()
    // 21 | click | linkText=C4: | 
    await driver.findElement(By.linkText("C4:")).click()
    // 22 | click | linkText=20: | 
    await driver.findElement(By.linkText("20:")).click()
    // 23 | click | linkText=20.1: | 
    await driver.findElement(By.linkText("20.1:")).click()
    // 24 | click | linkText=20.4: | 
    await driver.findElement(By.linkText("20.4:")).click()
    // 25 | click | linkText=20.41: | 
    await driver.findElement(By.linkText("20.41:")).click()
    // 26 | click | id=SwissDRG | 
    await driver.findElement(By.id("SwissDRG")).click()
    // 27 | mouseOver | id=SwissDRG | 
    {
      const element = await driver.findElement(By.id("SwissDRG"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 28 | mouseOut | id=SwissDRG | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 29 | click | linkText=MDC 05: | 
    await driver.findElement(By.linkText("MDC 05:")).click()
    // 30 | click | css=div:nth-child(3) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(3) #buttonversion")).click()
    // 31 | mouseOver | css=div:nth-child(3) #buttonversion | 
    {
      const element = await driver.findElement(By.css("div:nth-child(3) #buttonversion"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 32 | mouseOut | css=.show > #buttonversion | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 33 | click | id=V8.0 | 
    await driver.findElement(By.id("V8.0")).click()
    // 34 | click | linkText=MDC 06: | 
    await driver.findElement(By.linkText("MDC 06:")).click()
    // 35 | click | linkText=Andere Partition: | 
    await driver.findElement(By.linkText("Andere Partition:")).click()
    // 36 | click | linkText=G46: | 
    await driver.findElement(By.linkText("G46:")).click()
    // 37 | click | linkText=Andere Partition | 
    await driver.findElement(By.linkText("Andere Partition")).click()
    // 38 | click | linkText=G40: | 
    await driver.findElement(By.linkText("G40:")).click()
    // 39 | click | linkText=MDC 06 | 
    await driver.findElement(By.linkText("MDC 06")).click()
    // 40 | click | linkText=Andere Partition: | 
    await driver.findElement(By.linkText("Andere Partition:")).click()
    // 41 | click | linkText=G40: | 
    await driver.findElement(By.linkText("G40:")).click()
    // 42 | click | linkText=G40Z: | 
    await driver.findElement(By.linkText("G40Z:")).click()
    // 43 | mouseOver | linkText=eonum | 
    {
      const element = await driver.findElement(By.linkText("eonum"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 44 | click | id=TARMED | 
    await driver.findElement(By.id("TARMED")).click()
    // 45 | click | linkText=07: | 
    await driver.findElement(By.linkText("07:")).click()
    // 46 | click | css=ul > li:nth-child(2) | 
    await driver.findElement(By.css("ul > li:nth-child(2)")).click()
    // 47 | click | linkText=07.02: | 
    await driver.findElement(By.linkText("07.02:")).click()
    // 48 | click | linkText=07.0140: | 
    await driver.findElement(By.linkText("07.0140:")).click()
    // 49 | click | css=ul > li:nth-child(2) | 
    await driver.findElement(By.css("ul > li:nth-child(2)")).click()
    // 50 | click | linkText=07.0120: | 
    await driver.findElement(By.linkText("07.0120:")).click()
    // 51 | click | linkText=07.0260: | 
    await driver.findElement(By.linkText("07.0260:")).click()
    // 52 | click | linkText=07.0250: | 
    await driver.findElement(By.linkText("07.0250:")).click()
    // 53 | click | linkText=07 | 
    await driver.findElement(By.linkText("07")).click()
    // 54 | click | linkText=TARMED 01.09 | 
    await driver.findElement(By.linkText("TARMED 01.09")).click()
    // 55 | click | linkText=11: | 
    await driver.findElement(By.linkText("11:")).click()
  })
  it('testing breadcrumbs fr', async function() {
    // Test name: testing breadcrumbs fr
    // Step # | name | target | value
    // 1 | open | /fr/ICD/ICD10-GM-2020/icd_chapters/ICD10-GM-2020 | 
    await driver.get("http://localhost:3000/fr/ICD/ICD10-GM-2020/icd_chapters/ICD10-GM-2020")
    // 3 | click | linkText=I: | 
    await driver.findElement(By.linkText("I:")).click()
    // 4 | click | linkText=A00-A09: | 
    await driver.findElement(By.linkText("A00-A09:")).click()
    // 5 | runScript | window.scrollTo(0,0) | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 6 | click | linkText=A01: | 
    await driver.findElement(By.linkText("A01:")).click()
    // 7 | click | linkText=A01.0: | 
    await driver.findElement(By.linkText("A01.0:")).click()
    // 8 | runScript | window.scrollTo(0,248) | 
    await driver.executeScript("window.scrollTo(0,248)")
    // 9 | click | linkText=A01.2: | 
    await driver.findElement(By.linkText("A01.2:")).click()
    // 10 | click | linkText=A01.3: | 
    await driver.findElement(By.linkText("A01.3:")).click()
    // 11 | click | linkText=A00-A09 | 
    await driver.findElement(By.linkText("A00-A09")).click()
    // 12 | click | linkText=A01: | 
    await driver.findElement(By.linkText("A01:")).click()
    // 13 | click | linkText=A01.0: | 
    await driver.findElement(By.linkText("A01.0:")).click()
    // 14 | mouseOver | linkText=eonum | 
    {
      const element = await driver.findElement(By.linkText("eonum"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 15 | click | linkText=I | 
    await driver.findElement(By.linkText("I")).click()
    // 16 | click | linkText=B00-B09: | 
    await driver.findElement(By.linkText("B00-B09:")).click()
    // 17 | click | linkText=B08: | 
    await driver.findElement(By.linkText("B08:")).click()
    // 18 | click | id=CHOP | 
    await driver.findElement(By.id("CHOP")).click()
    // 19 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion | 
    await driver.findElement(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion")).click()
    // 20 | click | id=CHOP_2018 | 
    await driver.findElement(By.id("CHOP_2018")).click()
    // 21 | click | linkText=C4: | 
    await driver.findElement(By.linkText("C4:")).click()
    // 22 | click | linkText=20: | 
    await driver.findElement(By.linkText("20:")).click()
    // 23 | click | linkText=20.1: | 
    await driver.findElement(By.linkText("20.1:")).click()
    // 24 | click | linkText=20.4: | 
    await driver.findElement(By.linkText("20.4:")).click()
    // 25 | click | linkText=20.41: | 
    await driver.findElement(By.linkText("20.41:")).click()
    // 26 | click | id=SwissDRG | 
    await driver.findElement(By.id("SwissDRG")).click()
    // 27 | mouseOver | id=SwissDRG | 
    {
      const element = await driver.findElement(By.id("SwissDRG"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 28 | mouseOut | id=SwissDRG | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 29 | click | linkText=MDC 05: | 
    await driver.findElement(By.linkText("MDC 05:")).click()
    // 30 | click | css=div:nth-child(3) #buttonversion | 
    await driver.findElement(By.css("div:nth-child(3) #buttonversion")).click()
    // 31 | mouseOver | css=div:nth-child(3) #buttonversion | 
    {
      const element = await driver.findElement(By.css("div:nth-child(3) #buttonversion"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 32 | mouseOut | css=.show > #buttonversion | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 33 | click | id=V8.0 | 
    await driver.findElement(By.id("V8.0")).click()
    // 34 | click | linkText=MDC 06: | 
    await driver.findElement(By.linkText("MDC 06:")).click()
    // 35 | click | linkText=Autre partition: | 
    await driver.findElement(By.linkText("Autre partition:")).click()
    // 36 | click | linkText=G46: | 
    await driver.findElement(By.linkText("G46:")).click()
    // 37 | click | linkText=Autre partition | 
    await driver.findElement(By.linkText("Autre partition")).click()
    // 38 | click | linkText=G40: | 
    await driver.findElement(By.linkText("G40:")).click()
    // 39 | click | linkText=MDC 06 | 
    await driver.findElement(By.linkText("MDC 06")).click()
    // 40 | click | linkText=Autre partition: | 
    await driver.findElement(By.linkText("Autre partition:")).click()
    // 41 | click | linkText=G40: | 
    await driver.findElement(By.linkText("G40:")).click()
    // 42 | click | linkText=G40Z: | 
    await driver.findElement(By.linkText("G40Z:")).click()
    // 43 | mouseOver | linkText=eonum | 
    {
      const element = await driver.findElement(By.linkText("eonum"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 44 | click | id=TARMED | 
    await driver.findElement(By.id("TARMED")).click()
    // 45 | click | linkText=07: | 
    await driver.findElement(By.linkText("07:")).click()
    // 46 | click | css=ul > li:nth-child(2) | 
    await driver.findElement(By.css("ul > li:nth-child(2)")).click()
    // 47 | click | linkText=07.02: | 
    await driver.findElement(By.linkText("07.02:")).click()
    // 48 | click | linkText=07.0140: | 
    await driver.findElement(By.linkText("07.0140:")).click()
    // 49 | click | css=ul > li:nth-child(2) | 
    await driver.findElement(By.css("ul > li:nth-child(2)")).click()
    // 50 | click | linkText=07.0120: | 
    await driver.findElement(By.linkText("07.0120:")).click()
    // 51 | click | linkText=07.0260: | 
    await driver.findElement(By.linkText("07.0260:")).click()
    // 52 | click | linkText=07.0250: | 
    await driver.findElement(By.linkText("07.0250:")).click()
    // 53 | click | linkText=07 | 
    await driver.findElement(By.linkText("07")).click()
    // 54 | click | linkText=TARMED 01.09 | 
    await driver.findElement(By.linkText("TARMED 01.09")).click()
    // 55 | click | linkText=11: | 
    await driver.findElement(By.linkText("11:")).click()
  })
})
