// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('PopUp', function() {
  let driver
  let n = 1000;
  function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    await driver.manage().setTimeouts( { implicit: 10000 } );
  })
  afterEach(async function() {
    await sleep(250);
    await driver.quit();
    await sleep(250);
  })
  it('PopUp', async function() {
    // Test name: PopUp
    // Step # | name | target | value | comment
    // 1 | open | /de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022 |  | 
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    await sleep(2*n);

    // 2 | setWindowSize | 1101x993 |  | 
    await driver.manage().window().setRect({ width: 2000, height: 1000 })
    await sleep(n);
    // 3 | mouseOver | css=.language-btn:nth-child(4) |  |
    {
      const element = await driver.wait(until.elementLocated(By.css(".language-btn:nth-child(4)")))
      await driver.actions({ bridge: true }).move({origin:element}).perform()
    }
    await sleep(n);
    // 4 | click | css=.language-btn:nth-child(2) |  |
    await driver.wait(until.elementLocated(By.css(".language-btn:nth-child(2)"))).click()
    await sleep(n);
    // 5 | click | id=buttonversion |  |
    await driver.wait(until.elementLocated(By.id("buttonversion"))).click()
    await sleep(n);
    // 6 | click | id=ICD10-GM-2021 |  |
    await driver.wait(until.elementLocated(By.id("ICD10-GM-2021"))).click()
    await sleep(n);
    // 7 | click | css=.modal-footer > .customButton |  |
    await driver.wait(until.elementLocated(By.css(".modal-footer > .customButton"))).click()
    await sleep(n);
    // 8 | click | id=buttonversion |  |
    await driver.wait(until.elementLocated(By.id("buttonversion"))).click()
    await sleep(n);
    // 9 | click | id=ICD10-GM-2019 |  |
    await driver.wait(until.elementLocated(By.id("ICD10-GM-2019"))).click()
    await sleep(n);
    // 10 | click | css=.langBtn:nth-child(1) |  |
    await driver.wait(until.elementLocated(By.css(".langBtn:nth-child(1)"))).click()
    await sleep(n);
    // 11 | mouseOver | css=div:nth-child(3) #buttonversion |  |
    {
      const element = await driver.wait(until.elementLocated(By.css("div:nth-child(3) #buttonversion")))
      await driver.actions({ bridge: true }).move({origin:element}).perform()
    }
    await sleep(n);
    // 12 | mouseOut | css=div:nth-child(3) #buttonversion |  |
    {
      const element = await driver.wait(until.elementLocated(By.id("main")))
            await driver.actions({ bridge: true }).move({origin:element}).perform()
    }
    await sleep(n);
    // 13 | click | css=.language-btn:nth-child(3) |  |
    await driver.wait(until.elementLocated(By.css(".language-btn:nth-child(3)"))).click()
    await sleep(n);
    // 14 | click | id=buttonversion |  |
    await driver.wait(until.elementLocated(By.id("buttonversion"))).click()
    await sleep(n);
    // 15 | click | id=ICD10-GM-2015 |  |
    await driver.wait(until.elementLocated(By.id("ICD10-GM-2015"))).click()
    await sleep(n);
    // 16 | click | css=.langBtn:nth-child(2) |  |
    await driver.wait(until.elementLocated(By.css(".langBtn:nth-child(2)"))).click()
    await sleep(n);
    // 17 | click | id=TARMED |  |
    await driver.wait(until.elementLocated(By.id("TARMED"))).click()
    await sleep(n);
    // 18 | click | css=.langBtn:nth-child(2) |  |
    await driver.wait(until.elementLocated(By.css(".langBtn:nth-child(2)"))).click()
    await sleep(n);
    // 19 | click | id=buttonversion |  |
    await driver.wait(until.elementLocated(By.id("buttonversion"))).click()
    await sleep(n);
    // 20 | click | id=ICD10-GM-2019 |  |
    await driver.wait(until.elementLocated(By.id("ICD10-GM-2019"))).click()
    await sleep(n);
    // 21 | click | css=.langBtn:nth-child(2) |  |
    await driver.wait(until.elementLocated(By.css(".langBtn:nth-child(2)"))).click()
    await sleep(n);
    // 22 | click | css=div:nth-child(3) #buttonversion |  |
    await driver.wait(until.elementLocated(By.css("div:nth-child(3) #buttonversion"))).click()
    await sleep(n);
    // 23 | mouseOver | css=div:nth-child(3) #buttonversion |  |
    {
      const element = await driver.wait(until.elementLocated(By.css("div:nth-child(3) #buttonversion")))
      await driver.actions({ bridge: true }).move({origin:element}).perform()
    }
    await sleep(n);
    // 24 | mouseOut | css=.show > #buttonversion |  |
    {
      const element = await driver.wait(until.elementLocated(By.id("main")))
      await driver.actions({ bridge: true }).move({origin:element}).perform()
    }
    await sleep(n);
    // 25 | click | id=V10.0 |  |
    await driver.wait(until.elementLocated(By.id("V10.0"))).click()
    await sleep(n);
    // 26 | click | css=.modal-footer > .customButton |  |
    await driver.wait(until.elementLocated(By.css(".modal-footer > .customButton"))).click()
    await sleep(n);
    // 27 | click | css=div:nth-child(2) > div > .catalogButtons > #buttonversion |  |
    await driver.wait(until.elementLocated(By.css("div:nth-child(2) > div > .catalogButtons > #buttonversion"))).click()
    await sleep(n);
    // 28 | click | id=CHOP_2021 |  |
    await driver.wait(until.elementLocated(By.id("CHOP_2021"))).click()
    await sleep(n);
    // 29 | click | css=.modal-footer > .customButton |  |
    await driver.wait(until.elementLocated(By.css(".modal-footer > .customButton"))).click()
    await sleep(n);
  })
  it('PopUp mobile', async function() {
    // Test name: PopUp mobile
    // Step # | name | target | value | comment
    // 1 | open | /de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022 |  | 
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    await sleep(2*n);
    // 2 | setWindowSize | 400x800 |  |
    await driver.manage().window().setRect({ width: 400, height: 800 })
    await sleep(n);
    // 3 | click | css=.language-btn:nth-child(2) |  |
    await driver.wait(until.elementLocated(By.css(".language-btn:nth-child(2)"))).click()
    await sleep(n);
    // 4 | click | id=mobilebutton version |  |
    await driver.wait(until.elementLocated(By.id("mobilebutton version"))).click()
    await sleep(n);
    // 5 | click | id=ICD10-GM-2021 |  |
    await driver.wait(until.elementLocated(By.id("ICD10-GM-2021"))).click()
    await sleep(n);
    // 6 | click | css=.langBtn:nth-child(1) |  |
    await driver.wait(until.elementLocated(By.css(".langBtn:nth-child(1)"))).click()
    await sleep(n);
    // 7 | click | css=.language-btn:nth-child(2) |  |
    await driver.wait(until.elementLocated(By.css(".language-btn:nth-child(2)"))).click()
    await sleep(n);
    // 8 | click | id=mobilebutton version |  |
    await driver.wait(until.elementLocated(By.id("mobilebutton version"))).click()
    await sleep(n);
    // 9 | click | id=ICD10-GM-2019 |  |
    await driver.wait(until.elementLocated(By.id("ICD10-GM-2019"))).click()
    await sleep(n);
    // 10 | click | css=.langBtn:nth-child(2) |  |
    await driver.wait(until.elementLocated(By.css(".langBtn:nth-child(2)"))).click()
    await sleep(n);
    // 11 | click | id=mobilebutton catalog |  |
    await driver.wait(until.elementLocated(By.id("mobilebutton catalog"))).click()
    await sleep(n);
    // 12 | mouseOver | id=mobilebutton catalog |  |
    {
      const element = await driver.wait(until.elementLocated(By.id("mobilebutton catalog")))
      await driver.actions({ bridge: true }).move({origin:element}).perform()
    }
    await sleep(n);
    // 13 | mouseOut | id=mobilebutton catalog |  |
    {
      const element = await driver.wait(until.elementLocated(By.id( "main")))
            await driver.actions({ bridge: true }).move({origin:element}).perform()
    }
    await sleep(n);
    // 14 | click | id=SwissDRG 2 |  |
    await driver.wait(until.elementLocated(By.id("SwissDRG 2"))).click()
    await sleep(n);
    // 15 | click | id=mobilebutton version |  |
    await driver.wait(until.elementLocated(By.id("mobilebutton version"))).click()
    await sleep(n);
    // 16 | click | id=V11.0 |  |
    await driver.wait(until.elementLocated(By.id("V11.0"))).click()
    await sleep(n);
    // 17 | click | css=.customButton:nth-child(3) |  |
    await driver.wait(until.elementLocated(By.css(".customButton:nth-child(3)"))).click()
    await sleep(n);
  })
})
