// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('search', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('search de icd code (A15.3)', async function() {
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    await driver.findElement(By.css(".me-2")).click()
    await driver.findElement(By.css(".me-2")).sendKeys("A15.3")
    await driver.findElement(By.css(".searchResult:nth-child(1)")).click()
  })
  it('search it icd (letters)', async function() {
    await driver.get("http://localhost:3000/it/ICD/ICD10-GM-2020/icd_chapters/ICD10-GM-2020")
    await driver.findElement(By.css(".me-2")).click()
    await driver.findElement(By.css(".me-2")).sendKeys("asdf")
    await driver.findElement(By.css(".searchResult:nth-child(1)")).click()
  })
  it('search de icd ($$$)', async function() {
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    await driver.findElement(By.css(".me-2")).click()
    await driver.findElement(By.css(".me-2")).sendKeys("$$$")
    await driver.findElement(By.css(".searchResult:nth-child(1)")).click()
  })
  it('search en icd (letters)', async function() {
    await driver.get("http://localhost:3000/en/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    await driver.findElement(By.css(".me-2")).click()
    await driver.findElement(By.css(".me-2")).sendKeys("asdf")
    await driver.findElement(By.css(".searchResult:nth-child(1)")).click()
  })
  it('search fr icd (letters)', async function() {
    await driver.get("http://localhost:3000/fr/ICD/ICD10-GM-2020/icd_chapters/ICD10-GM-2020")
    await driver.findElement(By.css(".me-2")).click()
    await driver.findElement(By.css(".me-2")).sendKeys("letters")
    await driver.findElement(By.css(".searchResult:nth-child(1)")).click()
  })
  it('search de icd (letters)', async function() {
    await driver.get("http://localhost:3000/de/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    await driver.findElement(By.css(".me-2")).click()
    await driver.findElement(By.css(".me-2")).sendKeys("letters")
    await driver.findElement(By.css(".searchResult:nth-child(1)")).click()
  })
  it('search en icd ($$$)', async function() {
    await driver.get("http://localhost:3000/en/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    await driver.findElement(By.css(".me-2")).click()
    await driver.findElement(By.css(".me-2")).sendKeys("$$$")
    await driver.findElement(By.css(".searchResult:nth-child(1)")).click()
  })
  it('search en icd code (A15.3)', async function() {
    await driver.get("http://localhost:3000/en/ICD/ICD10-GM-2022/icd_chapters/ICD10-GM-2022")
    await driver.findElement(By.css(".me-2")).click()
    await driver.findElement(By.css(".me-2")).sendKeys("A15.3")
    await driver.findElement(By.css(".searchResult:nth-child(1)")).click()
  })
  it('search fr icd ($$$)', async function() {
    await driver.get("http://localhost:3000/fr/ICD/ICD10-GM-2020/icd_chapters/ICD10-GM-2020")
    await driver.findElement(By.css(".me-2")).click()
    await driver.findElement(By.css(".me-2")).sendKeys("$$$")
    await driver.findElement(By.css(".searchResult:nth-child(1)")).click()
  })
  it('search fr icd code (A15.3)', async function() {
    await driver.get("http://localhost:3000/fr/ICD/ICD10-GM-2020/icd_chapters/ICD10-GM-2020")
    await driver.findElement(By.css(".me-2")).click()
    await driver.findElement(By.css(".me-2")).sendKeys("A15.3")
    await driver.findElement(By.css(".searchResult:nth-child(1)")).click()
  })
  it('search it icd ($$$)', async function() {
    await driver.get("http://localhost:3000/it/ICD/ICD10-GM-2020/icd_chapters/ICD10-GM-2020")
    await driver.findElement(By.css(".me-2")).click()
    await driver.findElement(By.css(".me-2")).sendKeys("$$$")
    await driver.findElement(By.css(".searchResult:nth-child(1)")).click()
  })
  it('search it icd code (A15.3)', async function() {
    await driver.get("http://localhost:3000/it/ICD/ICD10-GM-2020/icd_chapters/ICD10-GM-2020")
    await driver.findElement(By.css(".me-2")).click()
    await driver.findElement(By.css(".me-2")).sendKeys("A15.3")
    await driver.findElement(By.css(".searchResult:nth-child(1)")).click()
  })
})
